name: Default issue template
about: Regular issue. Use this template if no other templates fit your needs.
title: "CRS-(NUMBER-HERE)-[FEATURE NAME]"

## Personal checklist

1. Tests have been ran and all passed
2. Code has been bult according to wiki conventions
3. Code renders correctly in the browser. No console errors
4. Design has been checked on all browsers listed below

Add more here depending on your needs

## Desired effect

What do you want to achieve in this issue.

## Current behaviour

Describe the current state of this issue.

## Tested on
[ ] Chrome
[ ] Safari
[ ] Firefox
[ ] Edge